### ISSUE TITLE
Could not find a part of the path

### ISSUE THREAD

**Issue by speier** [Iristyle/Redis-win32-FxTestIntegration#1]
I got the error below when calling `var connectionInfo = RedisIntegration.HostManager.RunInstance();`
I assume something went wrong when generating the temp path.

> Could not find a part of the path C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\api\052337a3\f6653c62\assembly\dl3\89911f30\af004d62_eef9cc01..........\packages\RedisIntegration.0.2.0.0\tools\64bit\redis-server.exe

**Comment by Iristyle** [comment]
Sorry I missed your report.  Interesting -- I haven't run inside of a debugger / ASP.NET like that.  I presume that's your environment?

I'll take a look later today and see if I can repro / fix -- sorry about that!

**Comment by speier** [comment]
Ok, I know it's not much, but that's all I got, but I am willing to help you if you can't reproduce the error, just let me know. Thank you!

**Comment by Iristyle** [comment]
Sorry it took so long to get around to scoping this out... we've updated the package with Redis 2.4.11 from MS Open Tech, and changed how the redis executable is located (its now shipped as an embedded resource).  This should appease the ASP.NET dev / build cycle.. and test runners.

Let us know if it works out -- thanks!
